import React from 'react'
import Header from './Header'
import Head from 'next/head'

function Layout({children, page}) {
  return (
    <div className="layout">
      <Head>
          <title>Qwizard</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        {children}
    </div>
  )
}

export default Layout